os: osx
osx_image: xcode9
language: objective-c

deploy:
  provider: script
  script: ./scripts/push.sh
  on:
    tags: true

podfile: Example/Podfile

before_install:
  - gem install cocoapods
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild -scheme SlideController -workspace Example/SlideController.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.0' build test | xcpretty --color
  - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
